name: Nudge

on:
  workflow_run:
    workflows: ['CI','CodeQL','Update Copyright Year']
    types: [completed]
    branches: [master]


jobs:
  nudge:
    runs-on: ubuntu-latest
    environment: nudge
    # if: (!(github.workflow == 'Update Copyright Year' && github.event == 'push'))
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Send notification
        uses: pavlovic-ivan/octo-nudge@v1
        with:
          webhooks: ${{ secrets.NUDGE_WEBHOOKS }}
          conclusions: 'failure,success'